### ISSUE TITLE
Can't logout if logged in over IP login

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#291]
@abaker-gavant @adistasio 
If I open the client from authenticated IP address and then login as an individual the client is still showing logged in via IP with no logout button.
If I come back to a session, created as above, saved in a cookie the logout button appears and the "Logged in Via IP" is hidden, but if logout button used browser shows {"message": "Internal server error"}
<img width="432" alt="Screenshot 2021-02-19 at 11 29 07" src="https://user-images.githubusercontent.com/70103034/108499937-fb3abb80-72a6-11eb-970f-8c8183c618bd.png">

The logout call passes back a new session ID, if this session ID is then used in the query string to the client then the client authenticates via the IP address but shows completely different information in the "Man" menu:
<img width="201" alt="Screenshot 2021-02-19 at 11 41 01" src="https://user-images.githubusercontent.com/70103034/108500231-5e2c5280-72a7-11eb-8354-570e56d98714.png">

**Comment by nrshapiro** [comment]
This appears to be fixed.  I'm authenticated via IP and when I login, it shows a logout button.  @jwoosnam if you disagree (it's your report, please reopen, but I'm trying to cleanup the issues database!)

**Comment by jwoosnam** [comment]
@abaker-gavant @adistasio
I think the logout problem was solved last week, but the current version is in stage and production are not working.
If a user is logged on via one of the primary methods IP URL or Federated and then logs in with a standard user all looks good, until they try to log out.  It appears to log out but must leave something in the cookies which leaves it in a half logged in state.  The only way to fix this is to clear my cookies.
<img width="191" alt="Screenshot 2021-03-16 at 10 59 58" src="https://user-images.githubusercontent.com/70103034/111298980-4d24f600-8647-11eb-8bf9-03232876b025.png">
<img width="262" alt="Screenshot 2021-03-16 at 11 00 10" src="https://user-images.githubusercontent.com/70103034/111298986-4e562300-8647-11eb-97ed-926e39dee478.png">

Is there any reason why logging out shouldn't clear all cookies?

**Comment by adistasio** [comment]
@jwoosnam I was unable to reproduce on stage with IP login. Do you have a federated user we can test with?

**Comment by bakerac4** [comment]
This has been fixed. There was bad HTML in one of the admin configs that broke the cookie

**Comment by jwoosnam** [comment]
@bakerac4 @nrshapiro @adistasio 
I am sorry to be fussy, but this really shouldn't be closed until it is fixed on Production, and I am still getting this issue on production.

**Comment by jwoosnam** [comment]
I have just tried this again, and it works if I login initially using a referrer URL, but is not working for a Federated login.

**Comment by bakerac4** [comment]
Be sure to clear your cookies manually before trying again @jwoosnam

**Comment by billdami** [comment]
@jwoosnam we tested federated login (via OpenAthens) on production from multiple machines, and it appears to be fixed there as well. As Adam mentioned, you'll need to manually clear all cookies on the domain in case you still had the "bad cookie" that was previously set by an invalid image tag in one of the Admin-controlled content areas.

**Comment by jwoosnam** [comment]
@bakerac4 @bakerac4 
Thanks for your efforts on this it does now seem to be working.  It sounds like it was one of those really frustrating issues!
I didn't clear my cookies previously because I had opened a new private window, which should've been good enough. I have now tested in both public and private windows and all seems okay.
